server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Compression gzip
    gzip on;
    gzip_types text/html text/css application/javascript application/json
               application/wasm font/woff2 image/svg+xml;
    gzip_min_length 1024;

    # Caching des assets statiques Flutter
    location ~* \.(js|css|wasm|png|ico|svg|ttf|woff2|json)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # Flutter SPA fallback — tout renvoie vers index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
